export interface Product {
  name: string;
  vendor: string;
  category: string;
  subcategory: string;
  ecosystem: string;
  notes?: string;
}

export const products: Product[] = [
  { name: "ConnectWise Manage", vendor: "ConnectWise", category: "PSA", subcategory: "Service Desk & Business Mgmt", ecosystem: "ConnectWise", notes: "Popular in EMEA mid/large MSPs" },
  { name: "Datto Autotask PSA", vendor: "Kaseya/Datto", category: "PSA", subcategory: "Service Desk & Business Mgmt", ecosystem: "Kaseya/Datto", notes: "Strong with Datto RMM" },
  { name: "Kaseya BMS", vendor: "Kaseya", category: "PSA", subcategory: "Business Mgmt", ecosystem: "Kaseya" },
  { name: "HaloPSA", vendor: "Halo", category: "PSA", subcategory: "Service Desk", ecosystem: "Halo", notes: "UK/EMEA momentum" },
  { name: "ServiceNow", vendor: "ServiceNow", category: "ITSM", subcategory: "Enterprise ITSM", ecosystem: "ServiceNow", notes: "Used by larger MSPs" },
  { name: "Jira Service Management", vendor: "Atlassian", category: "ITSM", subcategory: "Service Desk", ecosystem: "Atlassian" },
  { name: "Freshservice", vendor: "Freshworks", category: "ITSM", subcategory: "Service Desk", ecosystem: "Freshworks" },
  { name: "Zendesk", vendor: "Zendesk", category: "ITSM", subcategory: "Service Desk", ecosystem: "Zendesk", notes: "Some MSP desks" },
  { name: "ConnectWise Automate", vendor: "ConnectWise", category: "RMM", subcategory: "Endpoint & Infra Mgmt", ecosystem: "ConnectWise" },
  { name: "Datto RMM", vendor: "Kaseya/Datto", category: "RMM", subcategory: "Endpoint Management", ecosystem: "Kaseya/Datto" },
  { name: "N-able N-sight RMM", vendor: "N-able", category: "RMM", subcategory: "Unified RMM", ecosystem: "N-able" },
  { name: "N-able N-central", vendor: "N-able", category: "RMM", subcategory: "Advanced RMM", ecosystem: "N-able" },
  { name: "Kaseya VSA", vendor: "Kaseya", category: "RMM", subcategory: "Endpoint & Network Mgmt", ecosystem: "Kaseya" },
  { name: "NinjaOne", vendor: "NinjaOne", category: "RMM", subcategory: "Unified RMM/Endpoint", ecosystem: "NinjaOne" },
  { name: "Atera", vendor: "Atera", category: "RMM+PSA", subcategory: "All-in-one MSP", ecosystem: "Atera", notes: "Per-tech pricing" },
  { name: "Syncro", vendor: "Syncro", category: "RMM+PSA", subcategory: "All-in-one MSP", ecosystem: "Syncro" },
  { name: "SuperOps.ai", vendor: "SuperOps", category: "RMM+PSA", subcategory: "All-in-one MSP", ecosystem: "SuperOps" },
  { name: "Barracuda RMM", vendor: "Barracuda", category: "RMM", subcategory: "Security-focused RMM", ecosystem: "Barracuda" },
  { name: "TeamViewer Remote Management", vendor: "TeamViewer", category: "RMM", subcategory: "Add-on Monitoring/Patching", ecosystem: "TeamViewer" },
  { name: "Level RMM", vendor: "Level", category: "RMM", subcategory: "Cloud RMM", ecosystem: "Level", notes: "Emerging" },
  { name: "ConnectWise Control", vendor: "ConnectWise", category: "Remote Access", subcategory: "Remote Support", ecosystem: "ConnectWise", notes: "aka ScreenConnect" },
  { name: "N-able Take Control", vendor: "N-able", category: "Remote Access", subcategory: "Remote Support", ecosystem: "N-able" },
  { name: "TeamViewer", vendor: "TeamViewer", category: "Remote Access", subcategory: "Remote Support", ecosystem: "TeamViewer" },
  { name: "Splashtop", vendor: "Splashtop", category: "Remote Access", subcategory: "Remote Support", ecosystem: "Splashtop" },
  { name: "AnyDesk", vendor: "AnyDesk", category: "Remote Access", subcategory: "Remote Support", ecosystem: "AnyDesk" },
  { name: "SentinelOne Singularity", vendor: "SentinelOne", category: "Security", subcategory: "EDR/XDR", ecosystem: "SentinelOne" },
  { name: "CrowdStrike Falcon", vendor: "CrowdStrike", category: "Security", subcategory: "EDR/XDR", ecosystem: "CrowdStrike" },
  { name: "Microsoft Defender for Endpoint", vendor: "Microsoft", category: "Security", subcategory: "EDR/XDR", ecosystem: "Microsoft" },
  { name: "Sophos Intercept X", vendor: "Sophos", category: "Security", subcategory: "Endpoint/XDR", ecosystem: "Sophos", notes: "Managed via Sophos Central" },
  { name: "Bitdefender GravityZone", vendor: "Bitdefender", category: "Security", subcategory: "Endpoint/XDR", ecosystem: "Bitdefender" },
  { name: "ESET PROTECT", vendor: "ESET", category: "Security", subcategory: "Endpoint", ecosystem: "ESET" },
  { name: "Microsoft Defender for Office 365", vendor: "Microsoft", category: "Security", subcategory: "Email Security", ecosystem: "Microsoft" },
  { name: "Proofpoint Essentials", vendor: "Proofpoint", category: "Security", subcategory: "Email Security", ecosystem: "Proofpoint" },
  { name: "Mimecast", vendor: "Mimecast", category: "Security", subcategory: "Email Security & Archiving", ecosystem: "Mimecast" },
  { name: "Barracuda Email Protection", vendor: "Barracuda", category: "Security", subcategory: "Email Security", ecosystem: "Barracuda" },
  { name: "Cisco Umbrella", vendor: "Cisco", category: "Security", subcategory: "DNS/Web Security", ecosystem: "Cisco" },
  { name: "Cloudflare One", vendor: "Cloudflare", category: "Security", subcategory: "SASE/ZTNA/DNS", ecosystem: "Cloudflare" },
  { name: "Zscaler Internet Access", vendor: "Zscaler", category: "Security", subcategory: "SASE/Proxy", ecosystem: "Zscaler" },
  { name: "Palo Alto Prisma Access", vendor: "Palo Alto", category: "Security", subcategory: "SASE/ZTNA", ecosystem: "Palo Alto" },
  { name: "Fortinet FortiGate", vendor: "Fortinet", category: "Network Security", subcategory: "NGFW/UTM", ecosystem: "Fortinet", notes: "Cloud-managed options" },
  { name: "Cisco Meraki MX", vendor: "Cisco", category: "Network Security", subcategory: "Cloud-managed NGFW/SD-WAN", ecosystem: "Cisco Meraki" },
  { name: "Sophos XG Firewall", vendor: "Sophos", category: "Network Security", subcategory: "NGFW/UTM", ecosystem: "Sophos" },
  { name: "Palo Alto Networks NGFW", vendor: "Palo Alto", category: "Network Security", subcategory: "NGFW", ecosystem: "Palo Alto" },
  { name: "WatchGuard Firebox", vendor: "WatchGuard", category: "Network Security", subcategory: "NGFW/UTM", ecosystem: "WatchGuard" },
  { name: "Microsoft Entra ID", vendor: "Microsoft", category: "Identity", subcategory: "Cloud IAM/SSO/MFA", ecosystem: "Microsoft", notes: "Formerly Azure AD" },
  { name: "Okta", vendor: "Okta", category: "Identity", subcategory: "IDaaS/SSO/MFA", ecosystem: "Okta" },
  { name: "Duo Security", vendor: "Cisco", category: "Identity", subcategory: "MFA/ZTNA", ecosystem: "Cisco" },
  { name: "OneLogin", vendor: "OneLogin", category: "Identity", subcategory: "IDaaS/SSO", ecosystem: "OneLogin" },
  { name: "Ping Identity", vendor: "Ping", category: "Identity", subcategory: "SSO/MFA/Access", ecosystem: "Ping" },
  { name: "JumpCloud", vendor: "JumpCloud", category: "Identity", subcategory: "Directory-as-a-Service", ecosystem: "JumpCloud" },
  { name: "CyberArk", vendor: "CyberArk", category: "Identity", subcategory: "PAM", ecosystem: "CyberArk" },
  { name: "Acronis Cyber Protect Cloud", vendor: "Acronis", category: "Backup & DR", subcategory: "Unified Backup & Security", ecosystem: "Acronis" },
  { name: "Veeam Backup & Replication", vendor: "Veeam", category: "Backup & DR", subcategory: "VM/Cloud Backup", ecosystem: "Veeam" },
  { name: "Veeam Backup for Microsoft 365", vendor: "Veeam", category: "Backup & DR", subcategory: "M365 Backup", ecosystem: "Veeam" },
  { name: "Datto SIRIS", vendor: "Kaseya/Datto", category: "Backup & DR", subcategory: "BCDR Appliance+Cloud", ecosystem: "Kaseya/Datto" },
  { name: "Datto Cloud Continuity", vendor: "Kaseya/Datto", category: "Backup & DR", subcategory: "Endpoint Cloud Backup", ecosystem: "Kaseya/Datto" },
  { name: "N-able Backup", vendor: "N-able", category: "Backup & DR", subcategory: "Cloud Backup", ecosystem: "N-able" },
  { name: "Arcserve UDP", vendor: "Arcserve", category: "Backup & DR", subcategory: "Hybrid Backup", ecosystem: "Arcserve" },
  { name: "Keepit", vendor: "Keepit", category: "Backup & DR", subcategory: "SaaS Backup (M365, Google)", ecosystem: "Keepit", notes: "Strong in EMEA" },
  { name: "Dropsuite", vendor: "Dropsuite", category: "Backup & DR", subcategory: "SaaS Backup (M365)", ecosystem: "Dropsuite" },
  { name: "Microsoft 365", vendor: "Microsoft", category: "Productivity", subcategory: "Collaboration Suite", ecosystem: "Microsoft", notes: "Exchange, SharePoint, OneDrive, Teams" },
  { name: "Microsoft Intune", vendor: "Microsoft", category: "Device Mgmt", subcategory: "UEM/MDM", ecosystem: "Microsoft" },
  { name: "Microsoft 365 Defender", vendor: "Microsoft", category: "Security", subcategory: "XDR Suite", ecosystem: "Microsoft" },
  { name: "Microsoft Sentinel", vendor: "Microsoft", category: "Security", subcategory: "Cloud SIEM/SOAR", ecosystem: "Azure" },
  { name: "Microsoft 365 Lighthouse", vendor: "Microsoft", category: "MSP Tools", subcategory: "Multi-tenant M365 Mgmt", ecosystem: "Microsoft" },
  { name: "Nerdio Manager for MSP", vendor: "Nerdio", category: "Azure Mgmt", subcategory: "AVD/W365 Automation", ecosystem: "Microsoft Azure" },
  { name: "Datadog", vendor: "Datadog", category: "Monitoring", subcategory: "Full-stack Observability", ecosystem: "Datadog" },
  { name: "New Relic", vendor: "New Relic", category: "Monitoring", subcategory: "APM/Infra/Logs", ecosystem: "New Relic" },
  { name: "Dynatrace", vendor: "Dynatrace", category: "Monitoring", subcategory: "Software Intelligence", ecosystem: "Dynatrace" },
  { name: "LogicMonitor", vendor: "LogicMonitor", category: "Monitoring", subcategory: "Infra Monitoring", ecosystem: "LogicMonitor" },
  { name: "Auvik", vendor: "Auvik", category: "Monitoring", subcategory: "Network Monitoring", ecosystem: "Auvik" },
  { name: "PRTG Network Monitor", vendor: "Paessler", category: "Monitoring", subcategory: "Infra/Network Monitoring", ecosystem: "Paessler", notes: "Popular in DACH" },
  { name: "Zabbix", vendor: "Zabbix", category: "Monitoring", subcategory: "Open-source Monitoring", ecosystem: "Zabbix" },
  { name: "Elastic Cloud (ELK)", vendor: "Elastic", category: "Logging", subcategory: "Logs/Search/Visualization", ecosystem: "Elastic" },
  { name: "Grafana Cloud", vendor: "Grafana Labs", category: "Monitoring", subcategory: "Metrics/Visualization", ecosystem: "Grafana" },
  { name: "IT Glue", vendor: "Kaseya", category: "Documentation", subcategory: "MSP Documentation", ecosystem: "Kaseya" },
  { name: "Hudu", vendor: "Hudu", category: "Documentation", subcategory: "MSP Documentation", ecosystem: "Hudu", notes: "Self/Cloud-hosted" },
  { name: "Confluence", vendor: "Atlassian", category: "Documentation", subcategory: "Wiki/KB", ecosystem: "Atlassian" },
  { name: "N-able Passportal", vendor: "N-able", category: "Passwords", subcategory: "Password Mgmt + Docs", ecosystem: "N-able" },
  { name: "1Password Business", vendor: "1Password", category: "Passwords", subcategory: "Password Manager", ecosystem: "1Password" },
  { name: "Microsoft Power Automate", vendor: "Microsoft", category: "Automation", subcategory: "Workflow Automation", ecosystem: "Power Platform" },
  { name: "Azure Logic Apps", vendor: "Microsoft", category: "Automation", subcategory: "Integration/Orchestration", ecosystem: "Azure" },
  { name: "Zapier", vendor: "Zapier", category: "Automation", subcategory: "SaaS Integration", ecosystem: "Zapier" },
  { name: "Make (Integromat)", vendor: "Make", category: "Automation", subcategory: "SaaS Integration", ecosystem: "Make" },
  { name: "Ansible", vendor: "Red Hat", category: "Automation", subcategory: "Config Mgmt/IaC", ecosystem: "Red Hat" },
  { name: "Terraform", vendor: "HashiCorp", category: "Automation", subcategory: "IaC", ecosystem: "HashiCorp" },
  { name: "Rewst", vendor: "Rewst", category: "Automation", subcategory: "MSP Process Bots", ecosystem: "Rewst" },
  { name: "ScalePad", vendor: "ScalePad", category: "Asset Lifecycle", subcategory: "Warranty/Lifecycle Automation", ecosystem: "ScalePad" },
  { name: "Cisco Meraki (MX/MS/MR)", vendor: "Cisco", category: "Networking", subcategory: "Cloud-managed SD-WAN/Switch/Wi-Fi", ecosystem: "Cisco Meraki" },
  { name: "Aruba Central", vendor: "HPE Aruba", category: "Networking", subcategory: "Cloud-managed Switch/Wi-Fi", ecosystem: "Aruba" },
  { name: "Ubiquiti UniFi", vendor: "Ubiquiti", category: "Networking", subcategory: "Wi-Fi/Switch/Sec Gateway", ecosystem: "Ubiquiti", notes: "SMB/MSP" },
  { name: "Sophos Central Wireless/Switch", vendor: "Sophos", category: "Networking", subcategory: "Cloud-managed Network", ecosystem: "Sophos" },
  { name: "Google Workspace", vendor: "Google", category: "Productivity", subcategory: "Collaboration Suite", ecosystem: "Google" },
  { name: "Zoom", vendor: "Zoom", category: "UCaaS", subcategory: "Meetings/Phones", ecosystem: "Zoom" },
  { name: "Cisco Webex", vendor: "Cisco", category: "UCaaS", subcategory: "Meetings/Calling", ecosystem: "Cisco" },
  { name: "Slack", vendor: "Salesforce", category: "Collaboration", subcategory: "Messaging", ecosystem: "Salesforce" },
  { name: "Microsoft Purview", vendor: "Microsoft", category: "Compliance", subcategory: "DLP/Compliance/Records", ecosystem: "Microsoft" },
  { name: "Netskope", vendor: "Netskope", category: "Security", subcategory: "CASB/SSE", ecosystem: "Netskope" },
  { name: "Proofpoint CASB", vendor: "Proofpoint", category: "Security", subcategory: "CASB/DLP", ecosystem: "Proofpoint" },
  { name: "Microsoft Azure", vendor: "Microsoft", category: "Cloud Platform", subcategory: "IaaS/PaaS", ecosystem: "Microsoft", notes: "Strong EMEA presence" },
  { name: "Amazon Web Services", vendor: "Amazon", category: "Cloud Platform", subcategory: "IaaS/PaaS", ecosystem: "AWS" },
  { name: "Google Cloud Platform", vendor: "Google", category: "Cloud Platform", subcategory: "IaaS/PaaS", ecosystem: "Google" },
  { name: "OVHcloud", vendor: "OVHcloud", category: "Cloud Platform", subcategory: "IaaS", ecosystem: "OVHcloud", notes: "EU data residency" },
  { name: "IONOS Cloud", vendor: "IONOS", category: "Cloud Platform", subcategory: "IaaS", ecosystem: "IONOS", notes: "Germany/EU focus" },
  { name: "Hetzner Cloud", vendor: "Hetzner", category: "Cloud Platform", subcategory: "IaaS", ecosystem: "Hetzner", notes: "Popular in EU SMB" },
  { name: "JetPatch", vendor: "JetPatch", category: "Patch Mgmt", subcategory: "Endpoint Patching", ecosystem: "JetPatch" },
  { name: "PDQ Deploy & Inventory", vendor: "PDQ", category: "Endpoint Mgmt", subcategory: "Software Deployment", ecosystem: "PDQ", notes: "SMB-friendly" },
  { name: "ManageEngine Endpoint Central", vendor: "Zoho", category: "Endpoint Mgmt", subcategory: "UEM/Patch", ecosystem: "ManageEngine" },
  { name: "Jamf Pro", vendor: "Jamf", category: "Apple Mgmt", subcategory: "macOS/iOS MDM", ecosystem: "Apple", notes: "Common in EMEA edu/creative" },
  { name: "Exclaimer", vendor: "Exclaimer", category: "Email", subcategory: "Signatures for M365/Gmail", ecosystem: "Microsoft/Google", notes: "UK/EMEA strong" },
  { name: "Hornetsecurity 365 Total Protection", vendor: "Hornetsecurity", category: "Security", subcategory: "Email Security/Compliance", ecosystem: "Microsoft", notes: "EMEA vendor" },
  { name: "SpamTitan", vendor: "TitanHQ", category: "Security", subcategory: "Email Security", ecosystem: "Standalone", notes: "MSP-friendly" },
  { name: "Dropsuite Email Archiving", vendor: "Dropsuite", category: "Compliance", subcategory: "Email Archiving", ecosystem: "Dropsuite" },
  { name: "BrightGauge", vendor: "ConnectWise", category: "Reporting", subcategory: "Dashboards/QBR", ecosystem: "ConnectWise" },
  { name: "Power BI", vendor: "Microsoft", category: "Analytics", subcategory: "BI/Reporting", ecosystem: "Microsoft" },
  { name: "ConnectWise CPQ (Sell)", vendor: "ConnectWise", category: "CPQ", subcategory: "Quoting/Proposals", ecosystem: "ConnectWise" },
  { name: "Quoter", vendor: "Quoter", category: "CPQ", subcategory: "Quoting", ecosystem: "Quoter" },
  { name: "Datto Commerce (Gluh)", vendor: "Kaseya/Datto", category: "Commerce", subcategory: "Procurement/Quoting", ecosystem: "Kaseya/Datto", notes: "EMEA adoption" },
  { name: "ScopeStack", vendor: "ScopeStack", category: "CPQ", subcategory: "Services Scoping/SOW", ecosystem: "ScopeStack" },
  { name: "AvePoint Elements Platform", vendor: "AvePoint", category: "MSP Tools", subcategory: "Multi-tenant M365 Management", ecosystem: "Microsoft", notes: "Unified MSP portal" },
  { name: "Elements — User & Group Management", vendor: "AvePoint", category: "MSP Tools", subcategory: "Identity Ops (Multi-tenant)", ecosystem: "Microsoft", notes: "Provisioning, lifecycle, access control" },
  { name: "Elements — Device Management", vendor: "AvePoint", category: "MSP Tools", subcategory: "Intune Device Oversight", ecosystem: "Microsoft", notes: "Policy, compliance, posture" },
  { name: "Elements — License Management", vendor: "AvePoint", category: "MSP Tools", subcategory: "M365 License Optimization", ecosystem: "Microsoft", notes: "Usage analytics, right-sizing" },
  { name: "Elements — Workspace Management", vendor: "AvePoint", category: "MSP Tools", subcategory: "Teams/SharePoint Lifecycle", ecosystem: "Microsoft", notes: "Provisioning, naming, expiration" },
  { name: "Elements — Baselines", vendor: "AvePoint", category: "MSP Tools", subcategory: "Policy Baselines & Drift", ecosystem: "Microsoft", notes: "Standardization & continuous compliance" },
  { name: "AvePoint Cloud Backup for Microsoft 365", vendor: "AvePoint", category: "Backup & DR", subcategory: "SaaS Backup (M365)", ecosystem: "Microsoft", notes: "Exchange, SharePoint, OneDrive, Teams" },
  { name: "AvePoint Cloud Backup for Google Workspace", vendor: "AvePoint", category: "Backup & DR", subcategory: "SaaS Backup (Google)", ecosystem: "Google" },
  { name: "AvePoint Cloud Backup for Salesforce", vendor: "AvePoint", category: "Backup & DR", subcategory: "SaaS Backup (Salesforce)", ecosystem: "Salesforce" },
  { name: "AvePoint Cloud Governance", vendor: "AvePoint", category: "Governance", subcategory: "M365 Governance & Lifecycle", ecosystem: "Microsoft", notes: "Requests, approvals, lifecycle" },
  { name: "AvePoint Policies & Insights (PI)", vendor: "AvePoint", category: "Security", subcategory: "Permissions/DLP Analytics", ecosystem: "Microsoft", notes: "Exposure & sensitive data insights" },
  { name: "AvePoint FLY", vendor: "AvePoint", category: "Migration", subcategory: "Content & Tenant Migration", ecosystem: "Microsoft/Google", notes: "M365, SharePoint, Box/Google to M365" },
  { name: "AvePoint Cloud Records", vendor: "AvePoint", category: "Compliance", subcategory: "Records Management", ecosystem: "Microsoft", notes: "Retention, disposition, auditing" },
  { name: "AvePoint MyHub", vendor: "AvePoint", category: "Productivity", subcategory: "End-user Workspace Hub", ecosystem: "Microsoft", notes: "Unified access to Teams/Groups/Sites" },
  { name: "AvePoint EnPower", vendor: "AvePoint", category: "Administration", subcategory: "Delegated Admin & Insights", ecosystem: "Microsoft", notes: "Role-based admin & reporting" },
  { name: "CIPP (Community/Cloud Improved Partner Portal)", vendor: "CIPP", category: "MSP Tools", subcategory: "Multi-tenant M365/Azure Admin", ecosystem: "Microsoft", notes: "Open-source MSP portal for policies/baselines" },
  { name: "Augmentt Discover", vendor: "Augmentt", category: "SaaS Management", subcategory: "SaaS Discovery & Usage", ecosystem: "Multi-SaaS", notes: "Shadow IT visibility" },
  { name: "Augmentt Secure", vendor: "Augmentt", category: "SaaS Security", subcategory: "M365 Security Posture", ecosystem: "Microsoft", notes: "MFA, conditional access, hardening" },
  { name: "Augmentt Engage", vendor: "Augmentt", category: "SaaS Support", subcategory: "Helpdesk/Access Workflows", ecosystem: "Microsoft", notes: "Common admin tasks & automations" },
  { name: "Infinigate Cloud Inforcer", vendor: "Infinigate Cloud", category: "Commerce", subcategory: "Billing Reconciliation Automation", ecosystem: "Multi-vendor", notes: "Usage-to-invoice automation for MSPs" },
];
